# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pnLTxjKQtLW-kCQ8grfYejlWYmHevO1D
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from sklearn.model_selection import train_test_split
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab Notebooks

# =========================
# PCA FUNCTION
# =========================
def apply_pca(indep_X, n):
    sc = StandardScaler()
    indep_X_scaled = sc.fit_transform(indep_X)

    pca = PCA(n_components=n)
    pca_features = pca.fit_transform(indep_X_scaled)

    return pca_features

# =========================
# SPLIT FUNCTION
# =========================
def split_scalar(indep_X, dep_Y):
    X_train, X_test, y_train, y_test = train_test_split(
        indep_X, dep_Y, test_size=0.25, random_state=0
    )
    return X_train, X_test, y_train, y_test

# =========================
# CONFUSION MATRIX + REPORT
# =========================
def cm_prediction(classifier, X_test, y_test):
    y_pred = classifier.predict(X_test)

    from sklearn.metrics import confusion_matrix
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import classification_report

    cm = confusion_matrix(y_test, y_pred)
    Accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)

    return classifier, Accuracy, report, X_test, y_test, cm

# =========================
# LOGISTIC REGRESSION
# =========================
def logistic(X_train, y_train, X_test, y_test):
    from sklearn.linear_model import LogisticRegression

    classifier = LogisticRegression(random_state=0)
    classifier.fit(X_train, y_train)

    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test, y_test)
    return classifier, Accuracy, report, X_test, y_test, cm

# =========================
# SVM LINEAR
# =========================
def svm_linear(X_train, y_train, X_test, y_test):
    from sklearn.svm import SVC

    classifier = SVC(kernel='linear', random_state=0)
    classifier.fit(X_train, y_train)

    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test, y_test)
    return classifier, Accuracy, report, X_test, y_test, cm

# =========================
# SVM NON-LINEAR
# =========================
def svm_NL(X_train, y_train, X_test, y_test):
    from sklearn.svm import SVC

    classifier = SVC(kernel='rbf', random_state=0)
    classifier.fit(X_train, y_train)

    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test, y_test)
    return classifier, Accuracy, report, X_test, y_test, cm

# =========================
# NAIVE BAYES
# =========================
def Navie(X_train, y_train, X_test, y_test):
    from sklearn.naive_bayes import GaussianNB

    classifier = GaussianNB()
    classifier.fit(X_train, y_train)

    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test, y_test)
    return classifier, Accuracy, report, X_test, y_test, cm

# =========================
# KNN
# =========================
def knn(X_train, y_train, X_test, y_test):
    from sklearn.neighbors import KNeighborsClassifier

    classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
    classifier.fit(X_train, y_train)

    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test, y_test)
    return classifier, Accuracy, report, X_test, y_test, cm

# =========================
# DECISION TREE
# =========================
def Decision(X_train, y_train, X_test, y_test):
    from sklearn.tree import DecisionTreeClassifier

    classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
    classifier.fit(X_train, y_train)

    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test, y_test)
    return classifier, Accuracy, report, X_test, y_test, cm

# =========================
# RANDOM FOREST
# =========================
def random(X_train, y_train, X_test, y_test):
    from sklearn.ensemble import RandomForestClassifier

    classifier = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
    classifier.fit(X_train, y_train)

    classifier, Accuracy, report, X_test, y_test, cm = cm_prediction(classifier, X_test, y_test)
    return classifier, Accuracy, report, X_test, y_test, cm

# =========================
# RESULT TABLE
# =========================
def pca_Classification(acclog, accsvml, accsvmnl, accknn, accnav, accdes, accrf):
    dataframe = pd.DataFrame(
        index=['PCA'],
        columns=['Logistic', 'SVMl', 'SVMnl', 'KNN', 'Navie', 'Decision', 'Random']
    )

    for number, idex in enumerate(dataframe.index):
        dataframe['Logistic'][idex] = acclog[number]
        dataframe['SVMl'][idex] = accsvml[number]
        dataframe['SVMnl'][idex] = accsvmnl[number]
        dataframe['KNN'][idex] = accknn[number]
        dataframe['Navie'][idex] = accnav[number]
        dataframe['Decision'][idex] = accdes[number]
        dataframe['Random'][idex] = accrf[number]

    return dataframe

# =========================
# LOAD DATASET
# =========================
dataset1 = pd.read_csv("Wine.csv", index_col=None)

df2 = dataset1.copy()

# Convert categorical columns to dummy
df2 = pd.get_dummies(df2, drop_first=True)

# Display available columns to help identify the correct target variable
print("Available columns after get_dummies:", df2.columns.tolist())

# Features and target
# The original error was: KeyError: "['classification_yes'] not found in axis"
# This means the column 'classification_yes' does not exist in df2.
# Please inspect the output above and replace 'your_actual_target_column' with the correct name.
# For example, if your target column is named 'Class_2', you would use:
# indep_X = df2.drop('Class_2', axis=1)
# dep_Y = df2['Class_2']

# Corrected lines using the identified target column 'Customer_Segment'
indep_X = df2.drop('Customer_Segment', axis=1)
dep_Y = df2['Customer_Segment']

# =========================
# APPLY PCA
# =========================
# Determine the number of components for PCA. A common choice is to retain components explaining a certain percentage of variance, or a fixed number.
# For now, let's assume we want to reduce to 2 principal components. Adjust 'n_components' as needed.
n_components = 2 # Example: You might want to analyze variance explained to choose this.
pca_data = apply_pca(indep_X, n_components)

# =========================
# INITIALIZE ACCURACY LISTS
# =========================
acclog = []
accsvml = []
accsvmnl = []
accknn = []
accnav = []
accdes = []
accrf = []

# =========================
# SPLIT DATA
# =========================
X_train, X_test, y_train, y_test = split_scalar(pca_data, dep_Y)

# =========================
# TRAIN ALL MODELS
# =========================
classifier, Accuracy, report, X_test, y_test, cm = logistic(X_train, y_train, X_test, y_test)
acclog.append(Accuracy)

classifier, Accuracy, report, X_test, y_test, cm = svm_linear(X_train, y_train, X_test, y_test)
accsvml.append(Accuracy)

classifier, Accuracy, report, X_test, y_test, cm = svm_NL(X_train, y_train, X_test, y_test)
accsvmnl.append(Accuracy)

classifier, Accuracy, report, X_test, y_test, cm = knn(X_train, y_train, X_test, y_test)
accknn.append(Accuracy)

classifier, Accuracy, report, X_test, y_test, cm = Navie(X_train, y_train, X_test, y_test)
accnav.append(Accuracy)

classifier, Accuracy, report, X_test, y_test, cm = Decision(X_train, y_train, X_test, y_test)
accdes.append(Accuracy)

classifier, Accuracy, report, X_test, y_test, cm = random(X_train, y_train, X_test, y_test)
accrf.append(Accuracy)

def pca_Classification(acclog, accsvml, accsvmnl, accknn, accnav, accdes, accrf):
    dataframe = pd.DataFrame({
        'Logistic': [acclog[0]],
        'SVMl': [accsvml[0]],
        'SVMnl': [accsvmnl[0]],
        'KNN': [accknn[0]],
        'Navie': [accnav[0]],
        'Decision': [accdes[0]],
        'Random': [accrf[0]]
    }, index=['PCA'])

    return dataframe

def pca_classification(acclog, accsvm1, accsvmn1, accknn, accnav, accdes, accrf):
    dataframe = pd.DataFrame({
        'Logistic': [acclog[0]],
        'SVM1': [accsvm1[0]],
        'SVMn1': [accsvmn1[0]],
        'KNN': [accknn[0]],
        'Navie': [accnav[0]],
        'Decision': [accdes[0]],
        'Random': [accrf[0]]
    }, index=['PCA'])

    return dataframe

print(result)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# =========================
# 1. LOAD DATASET
# =========================
df = pd.read_csv("Wine.csv")   # change your file name

# Last column = target
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# =========================
# 2. TRAIN TEST SPLIT
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# =========================
# 3. SCALING
# =========================
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# =========================
# 4. PCA
# =========================
pca = PCA(n_components=2)   # change if needed
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

# =========================
# 5. MODELS
# =========================
models = {
    "Logistic": LogisticRegression(),
    "SVM Linear": SVC(kernel='linear'),
    "SVM RBF": SVC(kernel='rbf'),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42)
}

# =========================
# 6. TRAIN + PREDICT + METRICS
# =========================
results = []

for name, model in models.items():
    model.fit(X_train_pca, y_train)
    y_pred = model.predict(X_test_pca)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    rec = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)
    cm = confusion_matrix(y_test, y_pred)

    results.append([name, acc, prec, rec, f1])

    print(f"\n{name} Confusion Matrix:")
    print(cm)

# =========================
# 7. RESULTS TABLE
# =========================
results_df = pd.DataFrame(results, columns=["Model", "Accuracy", "Precision", "Recall", "F1 Score"])
print("\nFinal Results:")
print(results_df)

# =========================
# 8. ACCURACY BAR CHART
# =========================
plt.figure(figsize=(10,5))
plt.bar(results_df["Model"], results_df["Accuracy"])
plt.title("PCA Model Accuracy Comparison")
plt.xlabel("Models")
plt.ylabel("Accuracy")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# =========================
# 9. METRICS BAR CHART
# =========================
results_df.set_index("Model")[["Precision", "Recall", "F1 Score"]].plot(kind="bar", figsize=(10,5))
plt.title("Precision / Recall / F1 Score Comparison")
plt.ylabel("Score")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()